spring:
  application:
    name: shoppingcart
#  mvc:
#    servlet:
#      path: /api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/philips
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: ""

